version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # mkdir -p ~/docker/influxdb/data
      - /Users/jcarlson/docker/influxdb/data:/var/lib/influxdb
#    networks:
#      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
#    networks:
#      - monitoring
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
#    networks:
#      - monitoring
    volumes:
      # Data persistency
      # mkdir -p ~/docker/grafana/data
      - /Users/jcarlson/docker/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

#networks:
#  monitoring:

